### ISSUE TITLE
request for an  explanation

### ISSUE THREAD

**Issue by miladv33** [MarDSoul/ttt-android-request-bin-number#2]
Please tell me why you wrote the bindInformation function in this class. what is the purpose of this function when you can easily set the default string in the XML?
[DetailsFragment](https://github.com/MarDSoul/ttt-android-request-bin-number/blob/245db3916970814fd645441db1eb6ac036547d59/app/src/main/java/app/mardsoul/requestbin/ui/details/DetailsFragment.kt)

**Comment by MarDSoul** [comment]
Why is it default? I'm getting information from network in ViewModel class and call the function bindInformation() to insert the data into the layout. 
Of course, I could use DataBinding to set values into xml directly but I don't think this is a good practice.

**Comment by miladv33** [comment]
now I understood. It is very helpful to have this information. Thank you
